[project]
name = "actorium"
version = "0.0.1"
authors = [{ name = "Jonathan Slenders", email = "jonathan@slenders.be" }] 
description = "A modern implementation of Actors for distributed concurrency"
requires-python = ">=3.12,<3.15"
readme = "README.md"
license = { file = "LICENSE.md" }
keywords = ["actors"]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = [
   "pydantic",
   "anyio",
   "redis>=5.0.0",
   # Usage of typemap_extensions, see: https://github.com/msullivan/typemap-test/tree/main
   "typemap @ git+https://github.com/vercel/python-typemap.git",
]

[project.urls]
Homepage = "https://github.com/actorium/actorium"

[dependency-groups]
dev = [
    'pytest',
    #'mypy',
    "mypy @ git+https://github.com/msullivan/mypy-typemap.git",
]

[tool.mypy]
# --strict.
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
no_implicit_reexport = true
strict_equality = true
strict_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true

plugins = ['pydantic.mypy']

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.ruff]
target-version = "py312"
lint.select = [
    "W",        # pycodestyle warnings
    "I",        # isort
    "F",      # pyflakes
    "TID251",   # banned-api (TID251)
    "B012",     # break/continue/return in finally blocks.
    "B018",     # useless-expression.
    "B006",     # mutable-argument-default.
    "ASYNC251", # Don't allow time.sleep in async functions.
    "UP034",    # extraneous-parentheses.
    "RUF008",   # mutable-dataclass-default.
    "RET501",   # better return None handling
    "RET502",   # better return None handling
    "SIM201",
    "SIM202",   # simplify comparisons involving not
    "PIE",      # flake8-pie
    "DTZ",      # flake8-datetimez-dtz
    "PTH",      # flake8-use-pathlib
    "YTT",      # flake8-2020
]

[tool.ruff.lint.flake8-tidy-imports.banned-api]
"asyncio.Event".msg = "Use 'from anyio import Event' instead."
